#!/usr/bin/env python3

import os
import sys


class bcolors:
    def __init__(self):
        pass

    HEADER = '\033[95m'
    OKBLUE = '\033[94m'
    OKCYAN = '\033[96m'
    OKGREEN = '\033[92m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'


def run_script():
    print(f"{bcolors.HEADER}-----------------------CREATING RPODUCTION BUILD OF REACT APP-----------------------{bcolors.ENDC}")
    os.system('cd frontend')
    os.system('npm run build')
    print(f"{bcolors.HEADER}-----------------------PUSHING PRODUCTION BUILD TO GITHUB-----------------------{bcolors.ENDC}")
    os.system('git add .')
    os.system('git commit --allow-empty -m "automated script deploying app to Heroku"')
    os.system('git push')
    print(f"{bcolors.HEADER}-----------------------PUSHING PRODUCTION BUILD TO HEROKU-----------------------{bcolors.ENDC}")
    os.system('git push heroku master')
    print(f"{bcolors.OKGREEN}-----------------------SUCCESSFULLY HOSTED ON HEROKU-----------------------{bcolors.ENDC}")


if __name__ == '__main__':
    try:
        run_script()
    except KeyboardInterrupt:
        print(f"\n{bcolors.FAIL}ERROR: KeyboardInterrupt{bcolors.ENDC}")
        print(f"{bcolors.FAIL}SCRIPT ABORTED: entire script aborted{bcolors.ENDC}")
        sys.exit(0)
